### ISSUE TITLE
Weblinks selected image doesn't save

### ISSUE THREAD

**Issue by Webdongle** [joomla-extensions/weblinks#93] opened 2015-09-15 12:08 UTC
#### Steps to reproduce the issue
Install the Weblinks package into Joomla
Create a new weblink
In the images select an image
Save
Message says saved but image field shows empty

#### Expected result
Image field should show the image link that was selected

#### Actual result
Message says saved but image field shows empty

#### System information (as much as possible)
Windows 10 but sys info says 8
>PHP Built On 	Windows NT MY-COMPUTER 6.2 build 9200 (Windows 8 Home Premium Edition) i586
Database Version 	5.6.26
Database Collation 	utf8_general_ci
PHP Version 	5.5.28
Web Server 	Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.5.28
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.4.5 Development [ Ember ] 8-September-2015 21:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by Bakual** [comment] 2015-09-15 12:09
Imho duplicate of https://github.com/joomla-extensions/weblinks/pull/91

**Comment by Bakual** [comment] 2015-09-15 14:06
Closing as fixed with #91.

**Closed by Bakual** 2015-09-15 14:06 UTC
