### ISSUE TITLE
Weblinks categories: Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by toivo** [joomla-extensions/weblinks#393] opened 2018-11-26 13:10 UTC
### Steps to reproduce the issue
Install Weblinks 3.6.0 Package from https://extensions.joomla.org/extensions/extension/official-extensions/weblinks/ on Joomla 3.9.0 using PHP 7.2 and set to report PHP warnings.

Go to Components - Web Links and add any URL as New Web Link to the existing default category Uncategorised with default options, Save & Close.

Create a new menu item and select Web Links - List All Web Link Categories with default options, Save & Close.

Go to the front end and select the new link from the menu.

### Expected result
The list shows the default category Uncategorised.

### Actual result
The list shows the category Uncategorised after the PHP warning:
Warning: count(): Parameter must be an array or an object that implements Countable in C:\www\joomla380\components\com_weblinks\models\categories.php on line 95

### System information (as much as possible)
Joomla 3.9.0 and also Joomla 3.9.0 updated with Joomla_3.9.1-dev-Development-Update_Package.zip
PHP 7.2.11

### Additional comments
Fixed by inserting the following lines before line 95 in components/com_weblinks/models/categories.php

`	if (!is_array($this->_items))
	{
		$this->_items	= array();
	}`

Ref. topic "Weblinks Categories page - Warning: count() at https://forum.joomla.org/viewtopic.php?f=715&t=967481

**Comment by chmst** [comment] 2019-04-19 21:22
The issue is caused by a defective query.

Change the lines 153 - 154 by 

$query->select('CASE WHEN a.created_by_alias != "" THEN a.created_by_alias ELSE ua.name END AS author')
->select('ua.email', 'author_email')

And the $item is not empty.

**Comment by HLeithner** [comment] 2019-04-25 15:19
@chmst can you create a PR to fix this?

**Comment by chmst** [comment] 2019-04-25 20:05
Yes - but it was my fault - I have mixed up different issues.

**Comment by joomdonation** [comment] 2021-08-18 07:52
This issue was fixed in latest codebase, so I'm closing.

**Closed by joomdonation** 2021-08-18 07:52 UTC
