### ISSUE TITLE
PHP 8 errors

### ISSUE THREAD

**Issue by HLeithner** [joomla-extensions/weblinks#429] opened 2020-11-20 22:51 UTC
Errors are:
0 count(): Argument #1 ($var) must be of type Countable|array, null given
/components/com_weblinks/models/categories.php:95

0 Attempt to modify property "params" on null
/components/com_weblinks/views/category/tmpl/default_items.php:17

**Comment by bayareajenn** [comment] 2020-11-20 23:07
So...

1. Weblinks won't install from the Install from Web tab in com_installer in PHP8. It will install from package file.

2. Create category. Then create some weblinks.

3. Create Menu Items for any type of Weblinks menu item type and they throw the errors Harald mentioned above.

**Comment by alikon** [comment] 2020-11-21 09:33
i can confirm

> Weblinks won't install from the Install from Web tab in com_installer in PHP8. It will install from package file.

nor from install from URL

with 
Error
Unable to detect manifest file.

**Comment by HLeithner** [comment] 2020-11-21 09:44
does other extensions work? I test 2 other extensions without problems so I'm not sure if it's weblinks or joomla

**Comment by alikon** [comment] 2020-11-21 09:53
i've installed Akeeba Backup Core 7.4.0.1 (2020-11-18), and despite 

> PHP version 8.0 is newer than this software supports

seems to work

**Comment by bayareajenn** [comment] 2020-11-21 13:30
I installed two other extensions (Akeeba and JCE) via the Install from Web tab without issues. I agree with @alikon that I too got the message with Akeeba that 8.0 is newer than the software supports. JCE installs and displays but some functionality doesn't work presumably because it isn't ready for 8. 

So I think the issue is with Weblinks and not with Install from Web.

**Comment by ChristineWk** [comment] 2021-02-05 14:05
@HLeithner 

Here a Call Stack from German forum: https://forum.joomla.de/thread/13254-fehlermeldung-bei-aufrufen-von-kategorien-bei-addon-weblinks/?postID=83873#post83873<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/429">issues.joomla.org/tracker/weblinks/429</a>.</sub>

**Comment by joomdonation** [comment] 2021-08-18 08:41
With the recent commits, the two reported issues are fixed. So I'm closing this.

**Closed by joomdonation** 2021-08-18 08:41 UTC

**Comment by rotech1** [comment] 2022-09-01 00:02
I get this on a couple of Joomla 3.10.11 main menu items now ( just a couple, everything else is fine)...  Just testing migration to PHP8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/429">issues.joomla.org/tracker/weblinks/429</a>.</sub>

**Comment by rotech1** [comment] 2022-09-01 00:04
( Error: 0 - Attempt to modify property "params" on null ) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/429">issues.joomla.org/tracker/weblinks/429</a>.</sub>

**Comment by joomdonation** [comment] 2022-09-02 16:06
@rotech1 Could you please let us know exactly what we need to do to see that error? I just tested all menu item types of weblinks extension on Joomla 3.10.11 and PHP 8.1.9 and could not see the error you mentioned.

**Comment by ergotone** [comment] 2022-09-02 17:23
Sorry - false alarm, not weblinks specific -  it was caused by J3.10.11 menu only when type Category -**list** (CAtegory - blog &etc are fine...), tracked it down to old Gantry used by our template!

**Comment by joomdonation** [comment] 2022-09-03 09:07
@ergotone Ah, OK. Thanks for the update. I'm glad it is not a weblinks problem.

**Comment by Kikokuko** [comment] 2023-02-01 23:06
Confirming: Since my IP upgraded to PHP8.0 Weblinks reports error

"#0 Attempt to assign property "tagLayout" on null"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/weblinks/429">issues.joomla.org/tracker/weblinks/429</a>.</sub>

**Comment by joomdonation** [comment] 2023-02-02 02:01
@Kikokuko What Joomla and Weblinks version you are using? Could you please let us know step by step what we need to do to see the issue ourself?
