### ISSUE TITLE
Manfest file not found when installing on Joomla 4+

### ISSUE THREAD

**Issue by M4dKiwi** [joomla-extensions/weblinks#523] opened 2023-04-20 11:59 UTC
### Steps to reproduce the issue
Please confirm the installation by selecting the Install button

Extension Name
Weblinks
Install from
https://raw.githubusercontent.com/joomla-extensions/weblinks/master/manifest.xml

### Expected result
Install - confirmed

### Actual result
Joomla 4 is unable to detect manifest file

### System information (as much as possible)
I have not upgraded, but having no luck using the latest update of Joomla 4 installing weblinks :(

**Comment by richard67** [comment] 2023-05-15 17:14
I think the problem is that it needs to update the manifest.xml for targetplatform 4.3 here:

https://github.com/joomla-extensions/weblinks/blob/master/manifest.xml#L42

And possibly also here for 4.2. and 4.3:

https://github.com/joomla-extensions/weblinks/blob/master/manifest.xml#L28

@joomdonation Could you have a look? I am not sure about line 28, if this also needs to be changed. But line 42 needs to be modified for 4.3.

**Comment by richard67** [comment] 2023-05-15 17:19
P.S.: We should also prepare line 42 for tagretplatform 4.4. Regarding line 28 I normally would think it does not need any 4.x targetplatform, but it has the 4.0 and 4.1, that's what confused me. Maybe that was necessary for the pre-update checker and I don't remember that anymore?

**Comment by richard67** [comment] 2023-05-15 17:23
P.P.S.: I just see with help of git blame that it was PR #484 which added the targetplatform 4.1 to both lines. The initial version for 4.x was made with PR #462 , and that already had the 4.0 in both lines.

**Comment by richard67** [comment] 2023-05-15 17:41
Closing as having a pull request. Please check #524 by patching the update site of weblinks to the file of that PR: https://raw.githubusercontent.com/joomla-extensions/weblinks/4f5c286cb3d13387b4f0310fa1a0274a31d9e725/manifest.xml

**Closed by richard67** 2023-05-15 17:41 UTC
