### ISSUE TITLE
Version note is not saved 

### ISSUE THREAD

**Issue by chmst** [joomla-extensions/weblinks#441] opened 2021-07-22 12:45 UTC
### Steps to reproduce the issue
Enable Version history for weblinks (in options). 
The edit screen has a input field for version history

### Expected result
The input in version note is saved

### Actual result
The input in version note disappears

**Comment by joomdonation** [comment] 2021-08-16 11:39
Actually, it is saved and will be shown when you click on Versions button in the toolbar to see all versions of the item

It works in the same ways for all other extensions, so not a bug here :)

**Comment by joomdonation** [comment] 2021-08-18 05:20
Closing as this is not a bug as stated above.

**Closed by joomdonation** 2021-08-18 05:20 UTC
