### ISSUE TITLE
Hit, Clicks and Errors Oh My

### ISSUE THREAD

**Issue by jimijon** [joomla-extensions/weblinks#26] opened 2015-03-20 19:39 UTC
Hello -

What is the difference between hits and clicks? If I turn on Hits I see a hits marker. However, it never gets incremented. If I turn on clicks, it gives me an error and says website not found.

**Comment by therunnergit** [comment] 2015-10-30 14:05
`Count clicks` is a boolean option (yes / no). If it's enabled, each click on the weblink will be counted; if it's not, no count will happen.
`Hits` is the current count.

In other words:
* if `Count clicks` is set to `No`, `Hits` will always be 0
* if `Count clicks` is set to `Yes`, `Hits` will be incremented each time one clicks on the weblink.

I just tested and everything seems to be working fine: I cannot reproduce the error. We will add an automated test anyway just in case.

**Comment by Kubik-Rubik** [comment] 2015-10-31 10:12
Thank you for the explanation @therunnergit. I will close it here for now, don't hesitate to re-open it if you have further questions @jimijon!

**Closed by Kubik-Rubik** 2015-10-31 10:12 UTC
